from django.urls import path

from .views import (
    AboutView,
    ContactAdminReplyView,
    ContactAdminView,
    HomeView,
    InvitationCreateView,
    InvitationDeleteView,
    InvitationDetailView,
    InvitationExcelImportView,
    InvitationListView,
    InvitationUpdateView,
    SharedInvitationDetailView,
    SignUpView,
    StaffReportExcelView,
    StaffReportView,
    StaffReplySupportView,
    StaffToggleSupportView,
    SubscriptionDashboardView,
    contact_admin_thread_data,
    download_excel_template,
    download_invitation_image,
    download_qrcode,
    invitation_qr_preview,
    mark_printed,
    mark_shared,
    mark_support_thread_read,
    notifications_poll,
    payment_callback,
    set_language_preference,
    shared_invitation_qr_preview,
    staff_support_feed,
    start_payment,
    submit_site_rating,
    update_welcome_message,
)


app_name = "invitations"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("a-propos/", AboutView.as_view()),
    path("lang/", set_language_preference, name="set-language"),
    path("langue/", set_language_preference),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("inscription/", SignUpView.as_view()),
    path("plans/", SubscriptionDashboardView.as_view(), name="subscription"),
    path("abonnement/", SubscriptionDashboardView.as_view()),
    path("plans/welcome/", update_welcome_message, name="update-welcome-message"),
    path("abonnement/message-bienvenue/", update_welcome_message),
    path("messages/", ContactAdminView.as_view(), name="contact-admin"),
    path("contact-admin/", ContactAdminView.as_view()),
    path("messages/reply/", ContactAdminReplyView.as_view(), name="contact-admin-reply"),
    path("contact-admin/repondre/", ContactAdminReplyView.as_view()),
    path("messages/thread/", contact_admin_thread_data, name="contact-admin-thread"),
    path("contact-admin/thread/", contact_admin_thread_data),
    path("notifications/poll/", notifications_poll, name="notifications-poll"),
    path("review/", submit_site_rating, name="submit-rating"),
    path("notation/", submit_site_rating),
    path("dashboard/", StaffReportView.as_view(), name="staff-report"),
    path("staff/rapport/", StaffReportView.as_view()),
    path("dashboard/export/", StaffReportExcelView.as_view(), name="staff-report-excel"),
    path("staff/rapport/excel/", StaffReportExcelView.as_view()),
    path("dashboard/feed/", staff_support_feed, name="staff-support-feed"),
    path("staff/support/feed/", staff_support_feed),
    path(
        "dashboard/reply/<int:organizer_id>/",
        StaffReplySupportView.as_view(),
        name="staff-reply-support",
    ),
    path(
        "staff/rapport/repondre/<int:organizer_id>/",
        StaffReplySupportView.as_view(),
    ),
    path(
        "dashboard/toggle/<int:organizer_id>/",
        StaffToggleSupportView.as_view(),
        name="staff-toggle-support",
    ),
    path(
        "staff/rapport/toggle-support/<int:organizer_id>/",
        StaffToggleSupportView.as_view(),
    ),
    path(
        "dashboard/read/<int:organizer_id>/",
        mark_support_thread_read,
        name="staff-mark-support-read",
    ),
    path(
        "staff/rapport/lire/<int:organizer_id>/",
        mark_support_thread_read,
    ),
    path("pay/start/", start_payment, name="start-payment"),
    path("paiement/demarrer/", start_payment),
    path("pay/callback/<str:provider>/", payment_callback, name="payment-callback"),
    path("paiement/callback/<str:provider>/", payment_callback),
    path("guests/", InvitationListView.as_view(), name="list"),
    path("invites/", InvitationListView.as_view()),
    path("guests/import/", InvitationExcelImportView.as_view(), name="import-excel"),
    path("invites/import-excel/", InvitationExcelImportView.as_view()),
    path("guests/template/", download_excel_template, name="excel-template"),
    path("invites/modele-excel/", download_excel_template),
    path("create/", InvitationCreateView.as_view(), name="create"),
    path("nouvelle/", InvitationCreateView.as_view()),
    path("pass/<slug:slug>/", InvitationDetailView.as_view(), name="detail"),
    path("invitation/<slug:slug>/", InvitationDetailView.as_view()),
    path("pass/<slug:slug>/edit/", InvitationUpdateView.as_view(), name="update"),
    path("invitation/<slug:slug>/modifier/", InvitationUpdateView.as_view()),
    path("pass/<slug:slug>/delete/", InvitationDeleteView.as_view(), name="delete"),
    path("invitation/<slug:slug>/supprimer/", InvitationDeleteView.as_view()),
    path("pass/<slug:slug>/print/", mark_printed, name="print"),
    path("invitation/<slug:slug>/imprimer/", mark_printed),
    path("pass/<slug:slug>/share/", mark_shared, name="share"),
    path("invitation/<slug:slug>/partager/", mark_shared),
    path("pass/<slug:slug>/qr/", download_qrcode, name="download-qrcode"),
    path("invitation/<slug:slug>/qrcode/", download_qrcode),
    path("pass/<slug:slug>/qr/preview/", invitation_qr_preview, name="qr-preview"),
    path("invitation/<slug:slug>/qrcode/apercu/", invitation_qr_preview),
    path("pass/<slug:slug>/image/", download_invitation_image, name="download-image"),
    path("invitation/<slug:slug>/image/", download_invitation_image),
    path("i/<uuid:token>/", SharedInvitationDetailView.as_view(), name="shared-detail"),
    path("i/<uuid:token>/qrcode/", shared_invitation_qr_preview, name="shared-qr-preview"),
]
