# Generated by Django 5.2.13 on 2026-05-16 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('demo_card', 'Carte demo (Visa)'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('afrimoney', 'AfriMoney'), ('mpesa', 'M-Pesa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('demo_card', 'Carte demo (Visa)'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('afrimoney', 'AfriMoney'), ('mpesa', 'M-Pesa')], max_length=20, verbose_name='Operateur Mobile Money'),
        ),
    ]
