# Generated by Django 5.2.13 on 2026-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_invitation_is_read_invitation_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='receiver',
        ),
    ]
